version: '3.9'
services:
  users-api:
    build:
      context: ./users
      target: development
      dockerfile: Dockerfile
    env_file:
      - ./users/.env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./users:/app
      - /app/node_modules
    command: npm run start:dev
    entrypoint: /app/dev-entrypoint.sh
  auth-api:
    build:
      context: ./auth
      target: development
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env.dev
    ports:
      - "3001:3001"
    volumes:
      - ./auth:/app
      - /app/node_modules
    command: npm run start:dev
    entrypoint: /app/dev-entrypoint.sh