version: '3.9'
services:
  users-api:
    build:
      context: ./users
      target: production
      dockerfile: Dockerfile
    env_file:
      - ./users/.env.prod
    ports:
      - "3000:3000"
    command: npm run start
    entrypoint: /app/prod-entrypoint.sh
  auth-api:
    build:
      context: ./auth
      target: production
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env.prod
    ports:
      - "3001:3001"
    command: npm run start
    entrypoint: /app/prod-entrypoint.sh